export default {
	MAX_NAME_LENGTH: 8,
	MIN_NAME_LENGTH: 3,

	// Names of characters
	WIZARD: "Wizard",
	FINAL_BOSS: "Demon",
	ELF: "Elf",

	// These should not be changed
	PLAYER: "Player",
	NARRATOR: "Narrator",

	// Item types
	WEAPON: "WEAPON",
	ARMOUR: "ARMOUR",

	// Map constants
	VISUAL_MAP_WIDTH: 4,

	// Input constants
	DISABLED: "DISABLED",
	EXPECTING_NAME: "EXPECTING_NAME",
	EXPECTING_RACE: "EXPECTING_RACE",
	EXPECTING_WEAPON: "EXPECTING_WEAPON",
	EXPECTING_CONF: "EXPECTING_CONF",
	EXPECTING_ANYTHING: "EXPECTING_ANYTHING",
	EXPECTING_RESET: "EXPECTING_RESET",
	EXPECTING_MOVEMENT: "EXPECTING_MOVEMENT",
	EXPECTING_BATTLE: "EXPECTING_BATTLE",

	// Command constants
	EQUIP: "EQUIP",
	LOOK_AT: "LOOK AT",
	LOOK_AROUND: "LOOK AROUND",
	RESET: "RESET",
	OBSERVE: "OBSERVE",

	// Encounter constants
	TALK: "TALK",
	ATTACK: "ATTACK",

	// Dispatch constants
	QUEUE_MESSAGE: "QUEUE_MESSAGE",
	SHOW_MESSAGE: "SEND_MESSAGE",
	SET_NAME: "SET_NAME",
	SET_STATS: "SET_STATS",
	SET_INPUT: "SET_INPUT",
	QUEUE_ITEM: "QUEUE_ITEM",
	ADD_ITEM: "ADD_ITEM",
	REMOVE_ITEM: "REMOVE_ITEM",
	EQUIP_ITEM: "EQUIP_ITEM",
	PREP_STATS: "PREP_STATS",
	DISPLAY_STATS: "DISPLAY_STATS",
	PREP_INVENT: "PREP_INVENT",
	DISPLAY_INVENTORY: "DISPLAY_INVENTORY",
	PREP_MAP: "PREP_MAP",
	ADD_MAP: "ADD_MAP",
	MOVE: "MOVE",
	DAMAGE_NPC: "DAMAGE_NPC",
	DEFEAT_ENEMY: "DEFEAT_ENEMY",
	PREP_DAMAGE: "PREP_DAMAGE",
	DAMAGE_PLAYER: "DAMAGE_PLAYER",
	DUMMY_RESET: "DUMMY_RESET"
};
