module.exports = {
	MAX_NAME_LENGTH: 8,
	MIN_NAME_LENGTH: 3,

	// Input constants
	DISABLED: "DISABLED",
	EXPECTING_NAME: "EXPECTING_NAME",
	EXPECTING_RACE: "EXPECTING_RACE",
	EXPECTING_CONF: "EXPECTING_CONF",

	// Dispatch constants
	SHOW_MESSAGE: "SEND_MESSAGE",
	SET_NAME: "SET_NAME",
	SET_STATS: "SET_STATS",
	SET_INPUT: "SET_INPUT",
	DISPLAY_STATS: "DISPLAY_STATS"
};